apiVersion: v1
kind: Service
metadata:
  name: aiwam
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: aiwam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiwam
spec:
  selector:
    matchLabels:
      app: aiwam
  replicas: 6
  template:
    metadata:
      labels:
        app: aiwam
    spec:
      containers:
      - name: aiwam
        image: robertkarl/amiwearingamask:0c0f3ad
        ports:
        - containerPort: 80
